[2024-11-18T18:47:43.697+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T18:47:43.722+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ciril_group_test.create-db manual__2024-11-18T18:47:42.969628+00:00 [queued]>
[2024-11-18T18:47:43.734+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ciril_group_test.create-db manual__2024-11-18T18:47:42.969628+00:00 [queued]>
[2024-11-18T18:47:43.734+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-18T18:47:43.753+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): create-db> on 2024-11-18 18:47:42.969628+00:00
[2024-11-18T18:47:43.763+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Ciril_group_test', 'create-db', 'manual__2024-11-18T18:47:42.969628+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ciril_group_dag.py', '--cfg-path', '/tmp/tmpc6x69ooj']
[2024-11-18T18:47:43.767+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask create-db
[2024-11-18T18:47:43.771+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=187) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-18T18:47:43.773+0000] {standard_task_runner.py:72} INFO - Started process 188 to run task
[2024-11-18T18:47:43.826+0000] {task_command.py:467} INFO - Running <TaskInstance: Ciril_group_test.create-db manual__2024-11-18T18:47:42.969628+00:00 [running]> on host 6b4e62071061
[2024-11-18T18:47:43.919+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='Ciril_group_test' AIRFLOW_CTX_TASK_ID='create-db' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:47:42.969628+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:47:42.969628+00:00'
[2024-11-18T18:47:43.921+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T18:47:43.963+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-18T18:47:43.964+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/opt/***/create-ciril-db.sh']
[2024-11-18T18:47:43.973+0000] {subprocess.py:86} INFO - Output:
[2024-11-18T18:47:44.083+0000] {subprocess.py:93} INFO - permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Put "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/dt_eng_test-database-1/archive?noOverwriteDirNonDir=true&path=%2Ftmp": dial unix /var/run/docker.sock: connect: permission denied
[2024-11-18T18:47:44.104+0000] {subprocess.py:93} INFO - permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/dt_eng_test-database-1/json": dial unix /var/run/docker.sock: connect: permission denied
[2024-11-18T18:47:44.106+0000] {subprocess.py:93} INFO - Error executing SQL script.
[2024-11-18T18:47:44.106+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-18T18:47:44.126+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T18:47:44.127+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Ciril_group_test, task_id=create-db, run_id=manual__2024-11-18T18:47:42.969628+00:00, execution_date=20241118T184742, start_date=20241118T184743, end_date=20241118T184744
[2024-11-18T18:47:44.150+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T18:47:44.171+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T18:47:44.173+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
