[2024-11-18T14:49:04.844+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T14:49:04.866+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ciril_group.create-db manual__2024-11-18T14:49:04.354655+00:00 [queued]>
[2024-11-18T14:49:04.877+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ciril_group.create-db manual__2024-11-18T14:49:04.354655+00:00 [queued]>
[2024-11-18T14:49:04.877+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-18T14:49:04.899+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): create-db> on 2024-11-18 14:49:04.354655+00:00
[2024-11-18T14:49:04.915+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Ciril_group', 'create-db', 'manual__2024-11-18T14:49:04.354655+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/ciril_group_dag.py', '--cfg-path', '/tmp/tmpqs6y6tv1']
[2024-11-18T14:49:04.919+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask create-db
[2024-11-18T14:49:04.926+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=196) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-18T14:49:04.928+0000] {standard_task_runner.py:72} INFO - Started process 199 to run task
[2024-11-18T14:49:04.961+0000] {task_command.py:467} INFO - Running <TaskInstance: Ciril_group.create-db manual__2024-11-18T14:49:04.354655+00:00 [running]> on host aa723b0e8432
[2024-11-18T14:49:05.029+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Simo' AIRFLOW_CTX_DAG_ID='Ciril_group' AIRFLOW_CTX_TASK_ID='create-db' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T14:49:04.354655+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T14:49:04.354655+00:00'
[2024-11-18T14:49:05.030+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T14:49:05.045+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-18T14:49:05.046+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/opt/***/create-ciril-db.sh']
[2024-11-18T14:49:05.059+0000] {subprocess.py:86} INFO - Output:
[2024-11-18T14:49:05.082+0000] {subprocess.py:93} INFO - permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Put "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/database/archive?noOverwriteDirNonDir=true&path=%2Ftmp": dial unix /var/run/docker.sock: connect: permission denied
[2024-11-18T14:49:05.104+0000] {subprocess.py:93} INFO - permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/database/json": dial unix /var/run/docker.sock: connect: permission denied
[2024-11-18T14:49:05.107+0000] {subprocess.py:93} INFO - Error executing SQL script.
[2024-11-18T14:49:05.108+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-18T14:49:05.140+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T14:49:05.141+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Ciril_group, task_id=create-db, run_id=manual__2024-11-18T14:49:04.354655+00:00, execution_date=20241118T144904, start_date=20241118T144904, end_date=20241118T144905
[2024-11-18T14:49:05.183+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T14:49:05.197+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T14:49:05.198+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
